# Generated by Django 3.2.12 on 2023-10-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.ISK0kbvLUbQTc9hltD47fAHaF0%26pid%3DApi&f=1&ipt=e7d2f50ead449aba9ca7f6a38c98fd1e26684be07e2f7ff16e7faa7bd30638fb&ipo=images', max_length=500),
        ),
    ]
