# Generated by Django 3.2.12 on 2023-10-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.CAXQe3AgWFel1hIzxDZ6owEsDg%26pid%3DApi&f=1&ipt=48b7246ba67049a87fdd1474a4e493a8896e496d699eb31f64f8e5b9fef84833&ipo=images', max_length=500),
        ),
    ]
